version: "3.3"
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "5001:80"
    networks:
      - webnet
    depends_on:
      - web
  web:
    image: seanysdan/youtube-sync-backend:latest
    networks:
      - webnet
    environment:
      DB_HOST: db
      SERVER_URL: ec2-3-136-86-205.us-east-2.compute.amazonaws.com
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: YoutubeSync
    networks:
      - webnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./pgdata:/var/lib/postgresql/data
networks:
  webnet:
